apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: mytg
spec:
  replicas: 5
  selector:
    matchLabels:
     app: tomcat
  template:
    metadata:
     labels:
       app: tomcat
    spec:
     imagePullSecrets: mypasswd-for-custom-img
       - name: 
     containers:
       - name: tomcat
         image:  avinashgangarde9112/ci-cd-pipeline:BUILD_NUMBER
         ports:
          - containerPort: 8080
      
